services:
  # 容器名称
  mysql57:
    container_name: mysql57
    # 构建所使用的镜像
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      # 可以把mysql的数据目录映射到宿主机
      # - /data/mysql/db:/var/lib/mysql
    # 容器随docker自动启动
    restart: always
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
